fix php80

diff --git a/docker-php-ext-enable b/docker-php-ext-enable
--- a/docker-php-ext-enable
+++ b/docker-php-ext-enable
@@ -1,7 +1,8 @@
 #!/bin/sh
 set -e
 
-cd "$(php -r 'echo ini_get("extension_dir");')"
+extDir="$(php -d 'display_errors=stderr' -r 'echo ini_get("extension_dir");')"
+cd "$extDir"
 
 usage() {
 	echo "usage: $0 [options] module-name [module-name ...]"
@@ -10,7 +11,15 @@ usage() {
 	echo "       $0 --ini-name 0-apc.ini apcu apc"
 	echo
 	echo 'Possible values for module-name:'
-	echo $(find -maxdepth 1 -type f -name '*.so' -exec basename '{}' ';' | sort)
+	find -maxdepth 1 \
+			-type f \
+			-name '*.so' \
+			-exec basename '{}' ';' \
+		| sort \
+		| xargs
+	echo
+	echo 'Some of the above modules are already compiled into PHP; please check'
+	echo 'the output of "php -i" to see which modules are already loaded.'
 }
 
 opts="$(getopt -o 'h?' --long 'help,ini-name:' -- "$@" || { usage >&2 && false; })"
@@ -39,12 +48,8 @@ for module; do
 	if [ -z "$module" ]; then
 		continue
 	fi
-	if [ -f "$module.so" ] && ! [ -f "$module" ]; then
-		# allow ".so" to be optional
-		module="$module.so"
-	fi
-	if ! [ -f "$module" ]; then
-		echo >&2 "error: $(readlink -f "$module") does not exist"
+	if ! [ -f "$module" ] && ! [ -f "$module.so" ]; then
+		echo >&2 "error: '$module' does not exist"
 		echo >&2
 		usage >&2
 		exit 1
@@ -57,17 +62,38 @@ if [ -z "$modules" ]; then
 	exit 1
 fi
 
+pm='unknown'
+if [ -e /lib/apk/db/installed ]; then
+	pm='apk'
+fi
+
+apkDel=
+if [ "$pm" = 'apk' ]; then
+	if \
+		[ -n "$PHPIZE_DEPS" ] \
+		&& ! apk info --installed .phpize-deps > /dev/null \
+		&& ! apk info --installed .phpize-deps-configure > /dev/null \
+	; then
+		apk add --no-cache --virtual '.docker-php-ext-enable-deps' binutils
+		apkDel='.docker-php-ext-enable-deps'
+	fi
+fi
+
 for module in $modules; do
-	if nm -g "$module" | grep -q ' zend_extension_entry$'; then
+	moduleFile="$module"
+	if [ -f "$module.so" ] && ! [ -f "$module" ]; then
+		moduleFile="$module.so"
+	fi
+	if readelf --wide --syms "$moduleFile" | grep -q ' zend_extension_entry$'; then
 		# https://wiki.php.net/internals/extensions#loading_zend_extensions
-		line="zend_extension=$(readlink -f "$module")"
+		line="zend_extension=$module"
 	else
 		line="extension=$module"
 	fi
 
 	ext="$(basename "$module")"
 	ext="${ext%.*}"
-	if php -r 'exit(extension_loaded("'"$ext"'") ? 0 : 1);'; then
+	if php -d 'display_errors=stderr' -r 'exit(extension_loaded("'"$ext"'") ? 0 : 1);'; then
 		# this isn't perfect, but it's better than nothing
 		# (for example, 'opcache.so' presents inside PHP as 'Zend OPcache', not 'opcache')
 		echo >&2
@@ -76,8 +102,20 @@ for module in $modules; do
 		continue
 	fi
 
-	ini="/usr/local/etc/php/conf.d/${iniName:-"docker-php-ext-$ext.ini"}"
-	if ! grep -q "$line" "$ini" 2>/dev/null; then
+	case "$iniName" in
+		/*)
+			# allow an absolute path
+			ini="$iniName"
+			;;
+		*)
+			ini="$PHP_INI_DIR/conf.d/${iniName:-"docker-php-ext-$ext.ini"}"
+			;;
+	esac
+	if ! grep -qFx -e "$line" -e "$line.so" "$ini" 2>/dev/null; then
 		echo "$line" >> "$ini"
 	fi
 done
+
+if [ "$pm" = 'apk' ] && [ -n "$apkDel" ]; then
+	apk del --no-network $apkDel
+fi
