build and push

diff --git a/php70/Dockerfile b/php70/Dockerfile
--- a/php70/Dockerfile
+++ b/php70/Dockerfile
@@ -115,7 +115,7 @@ RUN set -x \
     && apk --no-cache add libmcrypt-dev unixodbc unixodbc-dev \
     # 配置GD库,开启更多图片支持
     && docker-php-ext-configure gd --enable-gd-native-ttf --enable-gd-jis-conv --with-jpeg-dir --with-png-dir --with-zlib-dir --with-freetype-dir --with-gd \
-    # 安装常用扩展
+    # 安装常用扩展 intl build fail with new icu-dev
     && docker-php-ext-install -j`grep -c ^processor /proc/cpuinfo` gd bcmath bz2 calendar dba exif gettext mcrypt mysqli pdo_mysql shmop soap sockets sysvmsg sysvsem sysvshm zip \
     # 从源码编译安装支持sasl的memcached扩展
     && curl -fSkL --retry 5 http://pecl.php.net/get/memcached-3.1.5.tgz -o /usr/src/memcached-3.1.5.tgz \
@@ -129,7 +129,7 @@ RUN set -x \
     && phpize && ./configure --enable-shared --disable-static && make -j`grep -c ^processor /proc/cpuinfo` && make install \
     && docker-php-ext-enable tideways_xhprof.so \
     # 使用pecl安装扩展
-    && pecl install redis yac-2.0.3 yaf xdebug-2.9.8 imagick mongodb-1.9.2 pdo_sqlsrv-5.3.0 \
+    && pecl install redis yac-2.0.3 yaf xdebug-2.7.2 imagick mongodb-1.9.2 pdo_sqlsrv-5.3.0 \
     && cd /usr/src && pecl download swoole-4.3.5 \
     && tar xzf /usr/src/swoole-4.3.5.tgz -C /usr/src \
     && cd /usr/src/swoole-4.3.5  \
@@ -137,6 +137,7 @@ RUN set -x \
     && docker-php-ext-enable memcached.so redis.so yac.so yaf.so swoole.so imagick.so opcache.so mongodb.so pdo_sqlsrv.so \
     # strip 所有扩展
     && { find /usr/local/php${BRANCH}/lib -type f -name "*.so" -exec strip --strip-all '{}' + || true; } 
+
 RUN set -x \
     # 安装composer
     && php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');" \
@@ -152,10 +153,10 @@ RUN set -x \
 
 RUN set -x \
     && apk add --no-cache --virtual .runupx upx  \
-    && { find /usr/local/bin -type f -perm +0111 -exec upx '{}' + || true; } \
-    && { find /usr/local/sbin -type f -perm +0111 -exec upx '{}' + || true; } \
-    && { find /usr/local/php${BRANCH}/bin -type f -perm +0111 -exec upx '{}' + || true; } \
-    && { find /usr/local/php${BRANCH}/sbin -type f -perm +0111 -exec upx '{}' + || true; } \
+    && { find /usr/local/bin -type f -perm +0111 -exec upx --best '{}' + || true; } \
+    && { find /usr/local/sbin -type f -perm +0111 -exec upx --best '{}' + || true; } \
+    && { find /usr/local/php${BRANCH}/bin -type f -perm +0111 -exec upx --best '{}' + || true; } \
+    && { find /usr/local/php${BRANCH}/sbin -type f -perm +0111 -exec upx --best '{}' + || true; } \
     && tar cf /tmp/pack.tar /usr/local/bin/composer /usr/local/bin/composer1 /usr/local/lib/libhashkit.so* /usr/local/lib/libmemcached.so* /usr/local/lib/libmemcachedutil.so* /usr/local/php${BRANCH}/bin /usr/local/php${BRANCH}/sbin /usr/local/php${BRANCH}/lib /usr/local/etc/php${BRANCH}
 
 FROM alpine:3.14 AS tmp
@@ -200,14 +201,14 @@ RUN set -x \
     && apk add --no-cache logrotate sudo tzdata git busybox-extras tar xz curl \
     && apk add --no-cache --virtual .persistent-deps $runDeps \
     && curl -fSkL --retry 5 https://github.com/just-containers/s6-overlay/releases/latest/download/s6-overlay-amd64.tar.gz| tar xfz - -C / \
-    && { find /usr/local/bin -type f -perm +0111 -exec upx '{}' + || true; } \
-    && { find /usr/local/php${BRANCH}/bin -type f -perm +0111 -exec upx '{}' + || true; } \
-    && { find /usr/local/sbin -type f -perm +0111 -exec upx '{}' + || true; } \
-    && { find /usr/local/php${BRANCH}/sbin -type f -perm +0111 -exec upx '{}' + || true; } \
-    && { find /usr/bin -type f -perm +0111 -exec upx '{}' + || true; } \
-    && { find /usr/sbin -type f -perm +0111 -exec upx '{}' + || true; } \
-    && { find /bin -type f -perm +0111 -exec upx '{}' + || true; } \
-    && { find /sbin -type f -perm +0111 -exec upx '{}' + || true; } \
+    && { find /usr/local/bin -type f -perm +0111 -exec upx --best '{}' + || true; } \
+    && { find /usr/local/php${BRANCH}/bin -type f -perm +0111 -exec upx --best '{}' + || true; } \
+    && { find /usr/local/sbin -type f -perm +0111 -exec upx --best '{}' + || true; } \
+    && { find /usr/local/php${BRANCH}/sbin -type f -perm +0111 -exec upx --best '{}' + || true; } \
+    && { find /usr/bin -type f -perm +0111 -exec upx --best '{}' + || true; } \
+    && { find /usr/sbin -type f -perm +0111 -exec upx --best '{}' + || true; } \
+    && { find /bin -type f -perm +0111 -exec upx --best '{}' + || true; } \
+    && { find /sbin -type f -perm +0111 -exec upx --best '{}' + || true; } \
     && apk del .runupx \
     # 日志目录
     && mkdir -p /usr/local/var/log/php-fpm/ \
